#!/bin/bash

set -e

APP=cpapp
SYSTEM_PASSWORD="$(openssl rand -base64 42)"
BLOCKS_OF_16GB=2

HANA_SETTINGS="$(cat <<EOF
{
	"hcu": "$BLOCKS_OF_16GB",
	"scriptserver": false,
	"dpserver": false,
	"docstore": false,
	"SystemPassword": "$SYSTEM_PASSWORD"
}
EOF
)"

echo "cf create-service hana-db standard $APP-hana -c "{ ... }"
cf create-service hana-db standard $APP-hana -c "$HANA_SETTINGS"

echo "[WARN] HANA database was created with random System user password."
echo "[WARN] It is recommended to switch off the System user:"
echo
echo "https://help.sap.com/viewer/cc53ad464a57404b8d453bbadbc81ceb/Cloud/en-US/21418824b23a401aa116d9ad42dd5ba6.html"
